### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by berry120**
Add digital ocean - they've provided me with enough credits for a basic VPS for a year for my open source project.

### CODE REVIEW

**Comment by ClydeDz** [comment]
@berry120, great find! Do you think that this might be a better link for [DigitalOcean's open-source initiative](https://developers.digitalocean.com/opensource/)?

**Comment by berry120** [comment]
Absolutely, that looks like a much better link 👍

**Comment by berry120** [comment]
Ok, in my bid to tidy up my forks I seem to have deleted the repo that this PR comes from - if you want to close this one I can create a new PR with that updated URL, or alternatively you can accept this and add the commit to change the URL afterwards? (Really don't mind either way this end.)

**Comment by ClydeDz** [comment]
@berry120, no worries. I've added a fresh commit with the required change and have added you as a co-author. Created a new PR for the same - #45. Will let @velikanov close this PR since I don't have access.

**Pull request closed without merging**
